name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install:all

      - name: Run tests
        run: npm test

      - name: Build extension
        run: npm run compile

  package:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install:all

      - name: Build extension
        run: npm run compile

      - name: Package extension
        run: |
          npm install -g @vscode/vsce
          vsce package

      - name: Upload vsix artifact
        uses: actions/upload-artifact@v2
        with:
          name: cline-extension
          path: '*.vsix'
